name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build extensions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Decode Keystore
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          echo "$SIGNING_KEY" | base64 -d > signingkey.jks

      - name: Build extensions
        env:
          ALIAS: ${{ secrets.ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: "extensions-apks"
          path: "**/*-release.apk"
          retention-days: 1

      - name: Clean up CI files
        run: rm signingkey.jks

  publish:
    name: Publish extension repo
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download APK artifacts
        uses: actions/download-artifact@v4
        with:
          name: extensions-apks
          path: repo/apk

      - name: Create Repo Index
        run: |
          cd repo
          # Download the official inspector tool
          curl -L "https://github.com/keiyoushi/extensions-inspector/releases/latest/download/Inspector.jar" -o Inspector.jar
          
          # Generate the index.json
          java -jar Inspector.jar "apk" "index.json" "tmp"
          
          # Clean up
          rm Inspector.jar
          rm -rf tmp

      - name: Deploy to Repo Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo
          publish_branch: repo
          user_name: 'GitHub Actions'
          user_email: 'actions@github.com'
          commit_message: 'Update extension repo'
          force_orphan: true